<main>
  <div class="container">
    <h1>Expérience <span><br>(cliquez sur les images pour plus de détail)</span></h1>

    <!-- zone info 1 -->
    <p>Ce que je sais faire</p>
    <div class="cadreFlip">
      <div class="flip3D">
        <div class="back" title="Vous pouvez retrouver l'image en cliquant de nouveau">
          <ul  class="enumFlip">
            <li>Ingénieur EPF, formation 3WA développeur intégrateur  WEB</li>
            <li>Certifiée ITIL V3, PRINCE2 et Scrum Master</li>
          </ul>
        </div>
        <div class="front" title="Cliquez pour en savoir plus ...">
          <img src="img/diplom3.png" alt="diplômes">
        </div>
      </div>
      <div class="flip3D">
        <div class="back" title="Vous pouvez retrouver l'image en cliquant de nouveau">
          <ul class="enumFlip">
            <li>HTML, CSS, javascript, jQuery, Ajax, PHP et mySQL, VBA pour Microsoft Office</li>
            <li>et anglais courant ...</li>
          </ul>
        </div>
        <div class="front" title="Cliquez pour en savoir plus ...">
          <img src="img/lang1.jpeg" alt="panel de langages informatiques">
        </div>
      </div>
      <div class="flip3D">
        <div class="back" title="Vous pouvez retrouver l'image en cliquant de nouveau">
          <ul  class="enumFlip">
            <li>Gestion de projets transverses et sous-traitance</li>
          </ul>
        </div>
        <div class="front" title="Cliquez pour en savoir plus ...">
          <img src="img/tableronde.jpg" alt="compétences de chef de projet">
        </div>
      </div>
      <div class="flip3D">
        <div class="back" title="Vous pouvez retrouver l'image en cliquant de nouveau">
          <ul class="enumFlip">
            <li>Assurer l'intégrité des données</li>
            <li>  + </li>
            <li>Reporting SQL, Microsoft Office et SAP BI</li>
          </ul>
        </div>
        <div class="front" title="Cliquez pour en savoir plus ...">
          <img src="img/qualite2.jpg" alt="qualité des données">
        </div>
      </div>
    </div>

    <!-- zone info 2 -->
    <p>Ce que j'aime faire</p>
    <div class="cadreFlip">
      <div class="flip3D">
        <div class="back" title="Vous pouvez retrouver l'image en cliquant de nouveau">
          <ul  class="enumFlip">
            <li>Réduire la complexité</li>
          </ul>
        </div>
        <div class="front" title="Cliquez pour en savoir plus ...">
          <img src="img/simpl1.jpg" alt="simplifier">
        </div>
      </div>
      <div class="flip3D">
        <div class="back" title="Vous pouvez retrouver l'image en cliquant de nouveau">
          <ul  class="enumFlip">
            <li>Trouver la bonne information au bon moment</li>
          </ul>
        </div>
        <div class="front" title="Cliquez pour en savoir plus ...">
          <img src="img/puzzle2.jpg" alt="panel de langages informatiques">
        </div>
      </div>
    </div>

    <!-- zone info 3 -->
    <p>Ce que je peux vous apporter</p>
    <div class="cadreFlip">
      <div class="flip3D">
        <div class="back" title="Vous pouvez retrouver l'image en cliquant de nouveau">
          <ul  class="enumFlip">
            <li>Mon expérience qui permet d'éviter des obstacles</li>
          </ul>
        </div>
        <div class="front" title="Cliquez pour en savoir plus ...">
          <img src="img/Obstacle2.jpg" alt="eviter les obstacles">
        </div>
      </div>
    </div>

  </div>


</main>
